### ISSUE TITLE
Support other DB types

### ISSUE THREAD

**Issue by davidmckenzie** [pagermon/pagermon#10]
* MySQL
* Mongo?
* DynamoDB + Lambda?

**Comment by davidf2002** [comment]
mysql/mariadb support would be great!

**Comment by davidmckenzie** [comment]
This is neat, could come in handy for DB upgrade scripts on other DB types: https://itnext.io/updating-an-sql-database-schema-using-node-js-6c58173a455a

**Comment by DanrwAU** [comment]
I've been playing around with this 
https://knexjs.org
Haven't got anywhere near being able to drop it in to replace the current stuff but it seems pretty neat. 
The only stumbling block will be the searching :(

**Comment by DanrwAU** [comment]
@davidmckenzie i started playing with Knex while i was bored today. 

Only did the DB creation stuff in db.js - api.js gives me a headache.....
https://github.com/DanrwAU/pagermon/blob/knex/server/db.js

Thoughts?

**Comment by davidmckenzie** [comment]
Ooh that looks pretty neat, and yeah, the API routes are gonna be the real herculean task lol. Will have to have a look at the knex docos at some point, see how it handles synchronicity. Does look super promising though

**Comment by DanrwAU** [comment]
@davidmckenzie Happy to close this one for 0.3.0?

**Comment by davidmckenzie** [comment]
Yep! I'd still like to do mongo support one day, but that'd be pretty much a complete fork so happy to close this. Thanks for all your work on it dude :)
