### ISSUE TITLE
Telegram: StatusCodeError:

### ISSUE THREAD

**Issue by pyrog** [pagermon/pagermon#157]
Some `Telegram: StatusCodeError: `returned by Telegram in the log file:
- `400`: wrong user/chat id
- `403`: bot stopped
- `404`: wrong API key

**Comment by pyrog** [comment]
Got status `400` when some characters are in the message:
```
message: 'Test 5b [',
message: 'Test 5f _',
message: 'Test 60 `',
```

**Comment by pyrog** [comment]
Also, what is the behaviour with message containing double quotes?
Are they escaped?

See #180

**Comment by davidmckenzie** [comment]
Just closing out support issues - if you still need any assistance feel free to jump on the new Discord server :) https://discord.gg/3VK7gSD

Alternatively - if you feel this is a bug in PagerMon (vs limitations of the Telegram API), please resubmit as a bug.
