### ISSUE TITLE
Double quote character is stripped from messages

### ISSUE THREAD

**Issue by pyrog** [pagermon/pagermon#180]
Double quote character `"` is stripped if contained in the message.
This happened when message is stored in database.

Note: If this character is added manually in the database, it is displayed correctly.

**Comment by davidmckenzie** [comment]
This is on purpose to reduce risk of SQLi attack, see line 499 in api.js. We could probably change this to replace with a similar char like `”` or something.

**Comment by davidmckenzie** [comment]
This may be resolved (or resolvable) when #174 goes to master - the duplicate checking SQL won't be as nasty any more :)

**Comment by DanrwAU** [comment]
> This may be resolved (or resolvable) when #174 goes to master - the duplicate checking SQL won't be as nasty any more :)

From reading https://stackoverflow.com/questions/49665023/does-knex-js-prevent-sql-injection Knex does prevent against injection. 
I'll have a play with it and see if i can cause one once i get it all working 👍

**Comment by DanrwAU** [comment]
Fixed in #274
