### ISSUE TITLE
Offer "Create Alias" when match was wildcard

### ISSUE THREAD

**Issue by eopo** [pagermon/pagermon#198]
I use two wildcard aliasses to filter out all the messages I don't need (RICs completely out of the normal scope that only receive control chars).
The one % matches everything and has a negative filter on it, the other 123% matches everything in the normal scope so they don't get dismissed. When I receive a message of an unknown RIC within my scope I can't create an alias for that within one click, because I'm only able to edit the 123%-Alias.
I'd propose that when an alias was matched by a _ or % wildcard the user can choose between editing the wildcard alias or creating a new alias with the exact adress in it.

**Comment by eopo** [comment]
Reverse

**Comment by DanrwAU** [comment]
This isn't as simple as it seems unfortunately. 

The actual alias is invisible to the front end that handles this - all we get is an aliasid. 

I was hoping to sneak this into 0.2.3 with the other bugfixes i'm doing but it'll need to wait for someone who knows what they are doing 😄
