### ISSUE TITLE
NotificationsEnabled State not saving

### ISSUE THREAD

**Issue by DanrwAU** [pagermon/pagermon#206]
**Describe the bug**
Cookies are not saving notification state correctly

**To Reproduce**
1. Disable browser notifications
2. Close browser and reopen
3. Check website - desktop notifications have been re-enabled

**Expected behavior**
Disabled notifications persist across browser sessions. 

**Screenshots**
Notifications Disabled
![image](https://user-images.githubusercontent.com/26653344/51093322-798a2100-17f6-11e9-8f2a-6475452f860b.png)

After browser restart
![image](https://user-images.githubusercontent.com/26653344/51093308-60817000-17f6-11e9-9205-57a0b1589cca.png)

**Environment information:**
- Browsers Affected: Chrome, Firefox latest
- Pagermon Version: Latest Release + master

**Additional context**
Believe this is due to the expiry being "session" on the cookie. 
Chrome shows expiry date for the field as 
![image](https://user-images.githubusercontent.com/26653344/51093341-adfddd00-17f6-11e9-82fc-3bcf1231df81.png)

**Comment by davidmckenzie** [comment]
Tested on my prod (few commits back) and dev (latest master) and both setting the cookie to 1969. Updated prod and still setting the expiry correctly.. weird.

Maybe we need to manually define expiry in the $cookies.put function: https://docs.angularjs.org/api/ngCookies/service/$cookies

**Comment by DanrwAU** [comment]
Closed from https://github.com/pagermon/pagermon/pull/213 because i have nothing better to do on a friday night 👍
