### ISSUE TITLE
Update favicon to have transparent background

### ISSUE THREAD

**Issue by davidmckenzie** [pagermon/pagermon#216]
**Describe the solution you'd like**
Switched to firefox recently, dark mode makes the white background of the favicon super obvious. The white bit outside of the bullhorn should be transparent.

**Describe alternatives you've considered**
Alternative is to ignore it because it's a favicon, who cares

**Additional context**
Probably see if I can knock out #50 at the same time

**Comment by DanrwAU** [comment]
I can handle this one this afternoon if need be - is this what your after?
![android-chrome-512x512](https://user-images.githubusercontent.com/26653344/51876799-f3590780-23bd-11e9-828a-5e826076fd7e.png)

**Comment by davidmckenzie** [comment]
Yah was thinking that but with the inside of the bullhorn filled, so it's just the outside white that's gone. Thanks dude <3

**Comment by DanrwAU** [comment]
No worries, i'll knock them all out when i get home 😉
