### ISSUE TITLE
Forget password

### ISSUE THREAD

**Issue by 112bzo** [pagermon/pagermon#226]
Hello please help.

I forgot my password ! how to find this one=

**Comment by marshyonline** [comment]
Hi
You can set` "encPass": ` back to `$2a$08$De/aXnQkZIEbQ9p8J22tHuzLltqIbsAxE2CGgRMPLaaIwwHmVrpsu`
in config.json and you password will be `changeme`

**Comment by DanrwAU** [comment]
Come see us in discord if this one is still an issue 😄
