### ISSUE TITLE
Switching to page 1 doesn't update URL

### ISSUE THREAD

**Issue by davidmckenzie** [pagermon/pagermon#229]
**Describe the bug**
Switching to page 1 doesn't update URL

**To Reproduce**
1. Go to main page
2. Click on page 2
3. Observe URL updates
4. Click on page 1
5. Observe URL stays at page 2

**Expected behavior**
URL should update to page=1

**Comment by DanrwAU** [comment]
This might be a mac thing, this works correctly for me in chrome, both using the back button in the browser and using the pagination buttons resets the url bar to the root url when going back to page 1

**Comment by davidmckenzie** [comment]
Works on Chrome, but not Safari or Firefox it seems. It's likely a thing with those browsers not liking "nothing" as the parameters - will update it to change to page=1 when you navigate back to page 1.
