### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 112bzo** [pagermon/pagermon#231]
How do i make my ip forword to a domain name. Like https://hrng.io/ 

My local IP is http://86.86.74.22:3010/ and i wil like to forword it to my domain www.p2k.nl 

How to do that.

Please help me

**Comment by davidmckenzie** [comment]
That's way out of scope to help you out with but take a look at some basic tutorials on nginx reverse proxying, DNS, etc. I run my install on an AWS EC2 instance with proxying taking place on the same server, but you could also run an rproxy from somewhere else to your local IP if preferred.
