### ISSUE TITLE
Fontawesome Icon Picker

### ISSUE THREAD

**Issue by davidmckenzie** [pagermon/pagermon#24]
Library I was planning on using is out of date, will need to research alternatives. For now, will place a link to the icon lists in the settings page.

https://github.com/itsjavi/fontawesome-iconpicker

**Comment by shutterfire** [comment]
For some reason I can only use a very limited set of icons. Icons with a dash in their name seem to not work at all (heart-rate, briefcase-medical or something like that)

**Comment by andrewerrington** [comment]
Came here looking for a solution, but I'll second the request to find and fix whatever it is that prevents fontawesome icons containing a dash in their name from working.

**Comment by DanrwAU** [comment]
> Came here looking for a solution, but I'll second the request to find and fix whatever it is that prevents fontawesome icons containing a dash in their name from working.

Haven't encountered this and we aren't aware of it. Open an new issue please

**Comment by eopo** [comment]
Closed by #514
