### ISSUE TITLE
Winston is in love with minute 4

### ISSUE THREAD

**Issue by DanrwAU** [pagermon/pagermon#250]
**Describe the bug**
Winston seems to have an obsession with the 4th minute of every hour. 

When the hour ticks over, winston will report the time as XX:04 where xx is the hour. 

**To Reproduce**
Read your logs, see logs like this. 
1|pagermon | 2019-04-03 17:39 +11:00: [pmon]  2019-04-03 17:04:86 

**Expected behavior**
Actual real times 

**Environment information:**
 - OS: Encountered on Windows and Linux
- Pagermon: Seen in v0.2.3 and above.

**Comment by marshyonline** [comment]
Replicated in two of my prod env's :sadpepe:

**Comment by DanrwAU** [comment]
@davidmckenzie any idea's with this one we've confirmed it's occuring in both v0.2.3 and v0.3.0.

**Comment by DanrwAU** [comment]
Fixed in #251
