### ISSUE TITLE
SQLite - Duplicate Message during alias refresh

### ISSUE THREAD

**Issue by DanrwAU** [pagermon/pagermon#256]
**Describe the bug**
Duplicate Message checking does not seem to work if messages are submitted while AliasRefresh is running. 

**To Reproduce**
Start long running aliasRefresh cycle and submit duplicate messages

**Expected behavior**
Duplicate messages filtered correctly. 

**Additional context**
Tested only in v0.2.3

**Comment by davidmckenzie** [comment]
I'm surprised messages even submit at all during the refresh tbh

**Comment by DanrwAU** [comment]
Me too, they seem to hold and be processed later ?

**Comment by DanrwAU** [comment]
I guess this could be related to #264 in that they are all submitted at the same time after the aliasRefresh finishes?

**Comment by DanrwAU** [comment]
I haven't seen this one since. closing as fixed i guess?
