### ISSUE TITLE
Gotify Plugin

### ISSUE THREAD

**Issue by dh47** [pagermon/pagermon#257]
Gotify is a self-hosted push notification service, think of it like PushBullet you have control over.

The Github repo:
https://github.com/gotify

Info on making a plugin with Gotify:
https://gotify.net/docs/plugin
https://gotify.net/docs/plugin-write

**Comment by ryaneast** [comment]
Just needs to be tested properly

**Comment by DanrwAU** [comment]
@ryaneast Open a WIP Pull Request 😉

**Comment by DanrwAU** [comment]
Will be released in V0.3.0
