### ISSUE TITLE
v0.3.0 - Duplicate Checking not working 

### ISSUE THREAD

**Issue by DanrwAU** [pagermon/pagermon#264]
**Describe the bug**
Duplicate checking not working when message limit is set to 0

**To Reproduce**
Set duplicate limit to 0, duplicate time to 60. 
Submit multiple copies of the same message (more than 2) 
Only the first is filtered, subsequent messages are submitted

**Expected behavior**
All messages are filtered correctly

**Additional context**
This **MAY** have already been fixed with the commits i've made but intermittently still seeing the issue. 
Issue for visibility. 
This one should block release of 0.3.0 for now.

**Comment by DanrwAU** [comment]
I'm thinking this may be an issue with incorrect time's on some of my receivers. 

I'll leave this open incase anyone else experiences this with v0.3.0

**Comment by DanrwAU** [comment]
Not sure what to do with this one, Problem seems to be messages that are being submitted at exactly the same time are not matching.

This wasn't an issue with v0.2.3 for some reason. 

Setting the message limit seems to make the problem worse.

@davidmckenzie  mind casting an eye over lines 530-573 in api.js ?

Also @pagermon/collaborators should we block v0.3.0 for this one?

**Comment by DanrwAU** [comment]
This seems to be related to the Timestamp calculations when the times are equal or close. 
Changing to only limit mode seems to solve the issue
![image](https://user-images.githubusercontent.com/26653344/56848290-712f9f00-692a-11e9-8406-473aff3191e9.png)

**Comment by davidmckenzie** [comment]
When you say exactly the same time... how exactly are we talking? Is it two separate receivers sending simultaneously or the sequential sending of a single receiver that gets two dupes in a row?

Guessing this is on MySQL too? Could be race condition just from MySQL being multithreaded. The insert and alias matching would take a few ms that might be enough time for the second message to start its insert too.

Could add a second layer of dupe checking - an array that holds the last x messages, but that wouldn't help if we go full multithread/clustered/load balanced. Good enough workaround for future problem solving with a proper MQ

**Comment by DanrwAU** [comment]
Multiple receivers, SQLite. 
Exactly the same second.... 

In testing it does see to pick up they are duplicates when using message count only mode, i think the problem is with this part of the querries

.where('timestamp', '>', timeDiff)

But i'm not sure whats wrong with it and i havent had enough sleep to begin figuring it out 😢

**Comment by davidmckenzie** [comment]
Hmm what about when it's only time limit and no message limit?

**Comment by DanrwAU** [comment]
Worse ... it never matches.
With both it's sometimes and with only message limit it works perfectly.

*head explodes*

**Comment by DanrwAU** [comment]
Never mind just had one duplicate with limit only.

I quit...

**Comment by davidmckenzie** [comment]
Well that's weird... are both the clients running latest copy? Maybe something weird with the timestamp parsing on client side. No hard to find whitespace on the dupe that was on limit only? Will have to do some sciencing I think

**Comment by DanrwAU** [comment]
All receivers are new reinstalls running identical bastardized versions of reader.sh for multifm.
:(

**Comment by DanrwAU** [comment]
Looked further into this today, i'm really at a loss, all the queries and bindings look correct when using the knex debugging. 
Only thing i can think of is that the messages are being inserted at exactly the same time (or close enough too).  
I'm wondering if i can build a delay into reader.js on each receiver to stagger the submissons. 
This shouldn't be an issue for duplicate messages being sent to pagermon by the same receiver, just my specific wierd use case.

**Comment by DanrwAU** [comment]
Confirmed that adding a 100ms delay between each receiver resolves the issue. 
(one firing at message receival, one at 200ms, one 300ms, one 400ms and one 500ms).

Maybe something to add to a known issue list and move on with release? @pagermon/collaborators opinions?

**Comment by marshyonline** [comment]
I would be against a random <=1s delay for messages

**Comment by DanrwAU** [comment]
Not sure it's required outside of this very specific use case.  
Possibly a setting in the reader config?

**Comment by davidmckenzie** [comment]
This might still help

> Could add a second layer of dupe checking - an array that holds the last x messages

Adds fair bit of complexity and doesn't solve the problem completely but would bring the race condition potential much lower.

Client side might be better - could add a 'rank' flag in the config. Rank 1 client is the primary feeder and goes instantly, 2 has 100ms delay, 3 has 200ms, etc.

Have you tried playing with how low you can drop the delay?

I'm also curious why this only started happening now. The only thing between the dupe check and the insert is the capcode identification bit (579-583). Maybe the knex version of that query is taking slightly longer to process.

**Comment by DanrwAU** [comment]
Or the non-knex is waiting for the previous submission to finish before starting?

Not sure

**Comment by davidmckenzie** [comment]
Good point, that sounds more likely

**Comment by davidmckenzie** [comment]
Could it need to be wrapped in a transaction? https://knexjs.org/#Transactions

**Comment by DanrwAU** [comment]
To be fair they possible should have been used to replace all the db.serialize commands ....

Oops?

**Comment by DanrwAU** [comment]
I've confirmed that messages including a \ always fail the duplicate check.

**Comment by DanrwAU** [comment]
Resolved in #303
