### ISSUE TITLE
alias failing to work. no id for alias 

### ISSUE THREAD

**Issue by framar1** [pagermon/pagermon#277]
on adding a alias with mysql database it would not save or implement.
on the alias screen the alias would not have a id number.
[alias mysql fix.txt](https://github.com/pagermon/pagermon/files/3150278/alias.mysql.fix.txt)
[VK6 pagermon log.txt](https://github.com/pagermon/pagermon/files/3150279/VK6.pagermon.log.txt)

yea i know i am not good at this

**Comment by DanrwAU** [comment]
Should be fixed in 0.3.2
