### ISSUE TITLE
Errors when enabling MessageRepeat Plugin

### ISSUE THREAD

**Issue by cwagner17** [pagermon/pagermon#289]
I have enabled the MessageRepeat plugin and have entered the remote Server URL, API Key and UUID Text. Whenever a message comes in the following error is displayed:

Message failed to deliver. StatusCodeError: 500 - "{\"error\":{\"name\":\"TypeError\",\"message\":\"Cannot read property 'statusCode' of undefined\",\"text\":\"TypeError: Cannot read property 'statusCode' of undefined\"}}"
Retrying in 1000 ms 

There does not seem to be much documentation on this plugin. Is it functional and if so what is causing the above error?

**Comment by DanrwAU** [comment]
Can you show us the settings your using?

Confirmed the second pagermon server is working correctly?

**Comment by cwagner17** [comment]
I can get my settings, but I wonder if it would be worthwhile to get a description of how to properly set it up.

**Comment by DanrwAU** [comment]
![image](https://user-images.githubusercontent.com/26653344/58328337-2fd0d780-7e75-11e9-93ac-2e121ea7c845.png)

**Comment by DanrwAU** [comment]
Also what version are both pagermon servers?

**Comment by cwagner17** [comment]
Thanks. It appears I had the URL incorrect as it is connecting and sending messages now. 

But the next issue I am running into is if the remote server is shut down or restarted it crashes the source server. It seems that if MessageRepeater is enabled the remote server needs to be connected or else the source will crash.

Everything is version 0.3.2-beta

Below is the error message that was logged:

[pmon]  2019-05-24 10:25:52  [34mdebug[39m : plugin: MessageRepeat
[pmon]  2019-05-24 10:25:52  [34mdebug[39m : RUNNING PLUGIN!
[pmon]  2019-05-24 10:25:52  [34mdebug[39m : { address: '0283746',
  message: 'test message',
  datetime: '1558707951',
  source: 'TEST',
  pluginData: {} }
[pmon]  2019-05-24 10:25:52  [34mdebug[39m : beforeMessage done
[pmon]  2019-05-24 10:25:52  [31merror[39m : uncaughtException: Cannot read property 'statusCode' of undefined
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/pi/pagermon/server/plugins/MessageRepeat.js:50:66)
    at self.callback (/home/pi/pagermon/server/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/pi/pagermon/server/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by DanrwAU** [comment]
Yeah I did pick that one up ... Something to fix

**Comment by cwagner17** [comment]
> Yeah I did pick that one up ... Something to fix

Should we close this ticket and open another one since this got off topic.

**Comment by marshyonline** [comment]
Leave this issue open, I'll work on a fix :)
Thanks for bringing it up, I thought I had addressed this is the initial release

**Comment by DanrwAU** [comment]
Fixed in #304 and Version 0.3.4
