### ISSUE TITLE
Swap agency and alias colums around and Hide/Show columns

### ISSUE THREAD

**Issue by s3m1s0n1c** [pagermon/pagermon#317]
Would be cool to be able to swap the Agency and Alias Columns around or even be able to hide show them

Eg TimeDate - Alias - Agency - Message 
instead of
TimeDate - Agency - Alias - Message

This could also be added to multi user so users can select there preferred column arrangement or use site default if not chosen

Thanks

**Comment by eopo** [comment]
How about defining Templates for Fields (e.G. Template for Alias including the icon and description or user defined only alias or whatever) that can be dynamically arranged, loaded and populated.

**Comment by s3m1s0n1c** [comment]
Closed due to this can be implemented in templates
