### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by 112bzo** [pagermon/pagermon#360]
**Describe the bug**

I can't login, the admin and chanceme credentionals don't work.

version : v0.3.6

**Comment by eopo** [comment]
Please try setting `hostname = ""` in server/config/config.json, restart the Server and try again. It’s a known problem though

**Comment by SloCompTech** [comment]
If anyone gets this error, set `hostname: ""` in `process.json`. Must be set to empty, not deleted.
