### ISSUE TITLE
WebSocket not working on new messages

### ISSUE THREAD

**Issue by all3kcis** [pagermon/pagermon#361]
See : https://github.com/pagermon/pagermon/blob/2f24061fd6f45dd01bfb0dce7f226dcccbd3e409/server/routes/api.js#L712-L756

This portion of code does not work inside the plugin callback.
Does it need to be in this callback? Can't it be output?
I think it should be out of the callback, as the message is already stored in the database, it can be sent to the socket.io

**Comment by davidmckenzie** [comment]
It's in the callback to force it to be synchronous - you're right though, probably doesn't need to be for the `after` plugins. Curious why it would be failing though, broken plugin?

**Comment by all3kcis** [comment]
I don't know, but I realized that it worked well out of the plugin callback :)

**Comment by marshyonline** [comment]
I'm unable to replicate this issue in the current master branch.
Do you have any local plugins that could be causing this issue?

**Comment by all3kcis** [comment]
Maybe, I was in development on https://github.com/pagermon/pagermon/pull/283
Now it seems to be working properly, really sorry.
It can be closed.
