### ISSUE TITLE
Readme to be updated with updated instructions for Docker

### ISSUE THREAD

**Issue by DanrwAU** [pagermon/pagermon#368]
**Describe the bug**
Readme needs to be updated for new docker method

**To Reproduce**
Read the readme

**Comment by SloCompTech** [comment]
Hi,
docker changes were merged to `v.0.3.7` branch so changes aren't seen in master yet. So please check `v0.3.7` and if it is anything unclear, I will try to write it better.

**Comment by DanrwAU** [comment]
My mistake, i had an old copy of 0.3.7 pulled down. Good Job!
