### ISSUE TITLE
Make search bar location user defineable

### ISSUE THREAD

**Issue by DanrwAU** [pagermon/pagermon#373]
**Is your feature request related to a problem? Please describe.**
Feature Request

**Describe the solution you'd like**
Add the ability to move the search bar to the top or bottom, selectable on the settings page

**Comment by s3m1s0n1c** [comment]
https://github.com/pagermon/pagermon/issues/319
I already had a issue open for this @DanrwAU

**Comment by DanrwAU** [comment]
Dammit, not having a good run am i
