### ISSUE TITLE
Alternative UI themes

### ISSUE THREAD

**Issue by Maaaaattee** [pagermon/pagermon#381]
**Is your feature request related to a problem? Please describe.**
A possible future UI theme feature that was discussed on Discord.

**Describe the solution you'd like**
Look at alternative themes for the main UI. Dark/Light etc..

**Describe alternatives you've considered**
Possibly look at integrating Bootstrap 4 into the new themes?

**Comment by wombatvic** [comment]
This would be great - would love a Dark Theme!

**Comment by DanrwAU** [comment]
Added theme support in #385
