### ISSUE TITLE
Raspberry Pi Image is missing Multimon-ng

### ISSUE THREAD

**Issue by marshyonline** [pagermon/pagermon#424]
**Describe the bug**
Raspberry Pi Image is missing Multimon-ng

**Expected behavior**
This should be installed

**Comment by s3m1s0n1c** [comment]
This has been fixed and re-uploaded to releases

<img width="660" alt="Screen Shot 2020-06-17 at 6 54 13 pm" src="https://user-images.githubusercontent.com/21308820/84878330-0791c780-b0cd-11ea-939b-109af44b3ebe.png">
<img width="697" alt="Screen Shot 2020-06-17 at 6 53 10 pm" src="https://user-images.githubusercontent.com/21308820/84878341-0bbde500-b0cd-11ea-87e4-95fb7dbaab6b.png">
