### ISSUE TITLE
A kind of search bar at the bottom left in PagerMon

### ISSUE THREAD

**Issue by marijn390** [pagermon/pagermon#430]
When you log in and, for example, go to the alias page, a kind of search bar will appear at the bottom left. This does not function further. I suspect it is a bug. Can anyone fix this? It is a bit annoying. Thanks in advance!

Screenshot is attached.
![Screenshot PagerMon](https://user-images.githubusercontent.com/68517513/88042126-bbaec400-cb4b-11ea-9e75-e6c76d8e3517.png)

**Comment by DanrwAU** [comment]
Fixed in #449
