### ISSUE TITLE
Invalid Time & date messages

### ISSUE THREAD

**Issue by crazyfella1** [pagermon/pagermon#437]
Hi there.

I have the pager on running on Ubuntu successfully. I have managed to get the messages from PDW in Windows to send the messages using the pdw2pagermon python script. Upon receiving messages I am getting invalid date and invalid time for the messages. Does anyone one have any knowledge on what format pagermon needs to be valid date and time. Both machines are in the correct time zone and reading the same date and time.

Thanks for your time and input.

**Comment by davidmckenzie** [comment]
It might be trying to parse a timestamp that's not actually a timestamp - try setting `useTimestamp` to false in the configs.

**Comment by crazyfella1** [comment]
Yea i had a look at that, because im running the python script there isn't the option to do that.

**Comment by marshyonline** [comment]
Can you provide screenshots of the settings you are using in PDW?

**Comment by crazyfella1** [comment]
![Python2](https://user-images.githubusercontent.com/71548621/93813106-b46c7980-fca6-11ea-8a71-267a0fe3d0c7.jpg)
![PDW](https://user-images.githubusercontent.com/71548621/93813112-b6ced380-fca6-11ea-9b9e-17f777379e59.JPG)

**Comment by jjeffhendryx** [comment]
![image](https://user-images.githubusercontent.com/23652327/94354298-b760c480-002e-11eb-8ea3-fa2e714d072f.png)
Change it so the When line reads as follows in the python script

**Comment by crazyfella1** [comment]
Thanks for that this solved my issue much appreciated!
