### ISSUE TITLE
Dynamic Columns not working on iPhone X

### ISSUE THREAD

**Issue by AndrewJ1990** [pagermon/pagermon#438]
**Is your feature request related to a problem? Please describe.**
When viewing on a mobile device the Alias column is not shown, thus not providing the name of the alias given to the capcode.

**Describe the solution you'd like**
Alias to be shown as a column, or as an option

**Describe alternatives you've considered**
An option to not show it, or shown at the end of the message for example as to not take up a column

**Additional context**

![image](https://user-images.githubusercontent.com/66349089/94240766-194dfb00-ff57-11ea-8948-203fc8e1c744.jpeg)

**Comment by DanrwAU** [comment]
Correct.

The columns are dynamic based on the width of the device screen. 

Try rotating your device 😉

**Comment by AndrewJ1990** [comment]
Tried that but still doesn't change. Is there anyway else for it to show them?

![image](https://user-images.githubusercontent.com/66349089/94240169-3e8e3980-ff56-11ea-9137-0298814e499f.png)

**Comment by DanrwAU** [comment]
Your device resolution is likely below the threshold to trigger the change.

Try "View desktop site" if your browser has it.
This disables the adaptive columns.

**Comment by AndrewJ1990** [comment]
I've tried that as well but makes no difference unfortunately. I'm using an iPhone X. If it can't be done that's fine, just a tad annoying

**Comment by DanrwAU** [comment]
I don't have an iPhone X so can only bae my tests off a test browser the supposedly emulates it and it seems to work.

Are you using some form of zoom above standard?

**Comment by AndrewJ1990** [comment]
No, all normal views and on iOS 14. It however works fine on my iPad Pro 11"

**Comment by davidmckenzie** [comment]
Sounds like something screwy in iOS Safari not communicating the viewport size to the CSS renderer. Would be keen to see other iPhone observations - I'm also android.

**Comment by s3m1s0n1c** [comment]
What happens if you use chrome or another browser?

**Comment by s3m1s0n1c** [comment]
Alias doesnt show on Iphone 8 with IOS 14

Its below the viewport max-width

**Comment by AndrewJ1990** [comment]
I just tried on Firefox. The same, and requesting desktop site made no difference.

**Comment by DanrwAU** [comment]
So this one is a quirk in the iPhone X and above - the device reports a smaller screen size to browsers (because of the notch) and makes it not show. 

Based on my testing fixing this and showing all columns is useless as the message is squashed. 

I'm about to open a PR to remove the noSmall checks on the alias column to fix just that one.
