### ISSUE TITLE
Multimon

### ISSUE THREAD

**Issue by mjs1987** [pagermon/pagermon#447]
Do I need install multimon ng, in pagermonimg?

**Comment by davidmckenzie** [comment]
Sure do, I just realised this isn't on the client wiki page, added :)

**Comment by mjs1987** [comment]
Oké so I need to install multimon and rtl sdr?

**Comment by davidmckenzie** [comment]
yep!

**Comment by mjs1987** [comment]
Nice it's working on my raspberry pi 4 b 2gb,

Where can I find the Dutch filter list?

Op di 17 nov. 2020 23:16 schreef davidmckenzie <notifications@github.com>:

**Comment by davidmckenzie** [comment]
Not a clue, can't help you there mate, good luck 😁

**Comment by mjs1987** [comment]
Oké thanx for information my friend

Op wo 18 nov. 2020 07:31 schreef davidmckenzie <notifications@github.com>:
