### ISSUE TITLE
Message search returning nil results via text matching

### ISSUE THREAD

**Issue by J1GGLYPUFFS** [pagermon/pagermon#459]
**Describe the bug**
When adding a text matching value IE: Hb or QD, clicking on the highlight of the message returns an ancient result and not the expected list of messages containing Hb etc. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Admin panel
2. Add an applicable text filter.
3. Return to messages and click the filter.

**Expected behaviour**
For all results to be available - Note: I have only observed this issue on small values (IE: Hb) with @@ALERT working fine.

**Screenshots**

![Image1](https://user-images.githubusercontent.com/77849123/106673195-5e6cf280-6605-11eb-90b0-6dc5ba749849.PNG)

![image2](https://user-images.githubusercontent.com/77849123/106673205-6167e300-6605-11eb-9497-beefb31b5fdc.PNG)

![Image3](https://user-images.githubusercontent.com/77849123/106673217-64fb6a00-6605-11eb-83f9-5626efd414d2.PNG)

**Environment information:**
 - OS: Raspberry Pi running Raspbian
 - Pagermon Version: 0.3.10

**Comment by DanrwAU** [comment]
This one is an issue with the search string only being 2 characters.

**Comment by J1GGLYPUFFS** [comment]
Hi Dan,

Thanks - Understood but I believe it should either work for all applicable results from the query IE: Hb or not at all

IE: If the users sending the message puts a symbol to start of their message then the filter works (see below)

![Image4](https://user-images.githubusercontent.com/77849123/106675370-210a6400-6609-11eb-8c1e-de7663f621fb.PNG)

**Comment by davidmckenzie** [comment]
It's due to the way searches tokenise strings, iirc it splits a string into a chunk of 3 or 4 characters and strips out special characters to form "words". We might have to artificially limit search string characters to prevent any results from showing. (different DBs probably react differently to this, too)
