### ISSUE TITLE
[Twitter Plugin] Twitter Post to thread when >240 Chars

### ISSUE THREAD

**Issue by MaxwellDPS** [pagermon/pagermon#461]
**Component:** Twitter Plugin

**Issue:** If the message is >240 chars, It will fail to post to Twitter

**Preferred solution:** Break message into chunks of 240 chars, and post as a twitter thread

**Describe alternatives you've considered**
Shorter messages - Not an option

**Comment by MaxwellDPS** [comment]
@davidmckenzie or @marshyonline Do we have anyone working on these?

**Comment by DanrwAU** [comment]
Nope.

Feel free to submit a PR.

**Comment by MaxwellDPS** [comment]
Please see pull #467  https://github.com/pagermon/pagermon/pull/467
