### ISSUE TITLE
Pagermon not compatible with newest Knex builds. 

### ISSUE THREAD

**Issue by DanrwAU** [pagermon/pagermon#475]
**Describe the bug**
New version of Knex is incompatible with current Pagermon.

Need to update to be compatible to apply security fixes in newer versions of Knex

**Comment by eopo** [comment]
I'd like to combine this with objection second try and also update a lot of promise-written-stuff to async/await

**Comment by DanrwAU** [comment]
> I'd like to combine this with objection second try and also update a lot of promise-written-stuff to async/await

Sounds horrible, have fun 🤣

**Comment by DanrwAU** [comment]
fixed in #572 can confirm, was horrible
