### ISSUE TITLE
Inconsistent Tests

### ISSUE THREAD

**Issue by eopo** [pagermon/pagermon#476]
https://github.com/pagermon/pagermon/blob/32a5c87e55a1f16aedf24f8ae24ec5633b22268b/server/test/routes.api.messages.id.test.js contains different requests to the api/messages/:id endpoint.
https://github.com/pagermon/pagermon/blob/32a5c87e55a1f16aedf24f8ae24ec5633b22268b/server/test/routes.api.messages.id.test.js#L45 wants the result of messages/:id to be an object
https://github.com/pagermon/pagermon/blob/32a5c87e55a1f16aedf24f8ae24ec5633b22268b/server/test/routes.api.messages.id.test.js#L69 wants the same result to be an array
https://github.com/pagermon/pagermon/blob/32a5c87e55a1f16aedf24f8ae24ec5633b22268b/server/test/routes.api.messages.id.test.js#L106 again wants it to be an array
In this case, object seems to make more sense, because we just really want one result.

Additionally, the file https://github.com/pagermon/pagermon/blob/32a5c87e55a1f16aedf24f8ae24ec5633b22268b/server/test/routes.api.messages.test.js should contain requests to the api/messages/ endpoint (Without :id)
However, in the line below, it does contain a request to an :id endpoint, that is already included in the other test file.https://github.com/pagermon/pagermon/blob/32a5c87e55a1f16aedf24f8ae24ec5633b22268b/server/test/routes.api.messages.test.js#L85

**Comment by DanrwAU** [comment]
Hmmm good catches, all seem to be issues with the idiot writing the tests (which was me 🤣 ) 

I'll sort these out shortly.. need to get my dev environment re-setup
