### ISSUE TITLE
running pagermon completely offline?  is this possible

### ISSUE THREAD

**Issue by burfordjay** [pagermon/pagermon#482]
I was testing and got everything up & running fine using PagermonPI v0.3.11 image.. but only when connected to the network/internet, is this normal?  (I am running Pi4 w/small monitor attached not accessing remotely)

I wanted to test this mobile and also at a location with no internet available - is there anyway that pagermon can be run offline from bootup w/o a network present?   

I install it as outlined, everything is fine but if attempt to boot without any network present, it just stops at chromium saying 'this site cant be reached... refused to connect' and just sits there.

** If I plug in my network cable and boot, it goes to browser, says same thing but then refreshes automatically and everything works perfect...  always get that "refused to connect" first either way, but it starts after a refresh automatically and everythings good.

I re-installed a couple times, thinking I made an error, but same results every time.

Perhaps pagermon requires a network connection to start?  (Or did I just miss something in the installation thats preventing me from booting -without- a network present)

Note:  I can boot with the network cable plugged in, and once everything is up and running, I can UNPLUG the network and everything is fine and works perfect offline, but it wont start running without a network cable plugged in.

Is a feature request that might be useful to others also? Or am I just setup wrong..

Amazing development.. thanks for everyones hard & dedicated work.

**Comment by davidmckenzie** [comment]
This should work... what URL is chrome trying to connect to? If it's listening on 127.0.0.1 then it should be fine. I haven't tried running the raspi image - going from Docker would definitely work since it would simulate a network internally

**Comment by geelongmicrosoldering** [comment]
the default for ubuntu, so in theory also raspbian, is to have a loopback interface, which binds 127.0.0.1

this should work fine as long as you are using the url `http://127.0.0.1:3000`
i know from my own testing (lightning blew up my modem), that it works fine on a network with no internet. but i have a lot of local services that use 127.0.0.1 without issue.

i suspect you are using `pagermonpi` or whatever host name in chromium.

Either that, or you have chromium opening before pagermon server has finished starting. that would definitely explain the "refused" response, because the port would be closed. I actually have a maintenance script that runs once a week where i need to monitor when the server is available. Here's how I do that:
```
# The /auth/login is important, or the request will redirect and your while loop will be indefinite
serverurl=http://127.0.0.1:3000/auth/login
while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' $serverurl)" != "200" ]]; do echo "Waiting for Server..."; sleep 5; done
# Do some stuff here, like open chromium
```

**Comment by marshyonline** [comment]
I don't believe loading the front end is possible without internet - all the libraries are included from CDN's

**Comment by geelongmicrosoldering** [comment]
> I don't believe loading the front end is possible without internet - all the libraries are included from CDN's

Ah yes, you would need to put your own copies of fontawesome, jquery ect and edit the templates. that would be it though right?

**Comment by marshyonline** [comment]
> > I don't believe loading the front end is possible without internet - all the libraries are included from CDN's
> 
> Ah yes, you would need to put your own copies of fontawesome, bootstrap, jquery ect and edit the templates. that would be it though right?

Yes, this would work - anything in https://github.com/pagermon/pagermon/blob/master/server/themes/default/views/global/header.ejs
needs to be replicated locally.
You could cheat this by creating a new theme with offline libraries instead of updating the default theme
