### ISSUE TITLE
Decode Filter active?

### ISSUE THREAD

**Issue by ChrisX1809** [pagermon/pagermon#494]
Hey,

ive got a problem with decoding messages in Pagermon. Used server in Docker and the client locally on the machine. Client runs with rtl_fm and multimon, but got some greyed messages in the log, that arent visible at the pagermon site. 

Is a standard filter active? Didnt find one.

![image](https://user-images.githubusercontent.com/73432338/149400845-3ba391a8-9472-489d-be8f-fc5f72f9dd05.png)

![image](https://user-images.githubusercontent.com/73432338/149401222-7fb20420-090e-4cd8-ba84-7b27e07c7320.png)

I use  PagerMon 0.3.11-beta, multimon-NG latest.

**Comment by takenalias** [comment]
I'm pretty sure that is because they are not decoding properly. So the
signal is not strong or clear enough or maybe the front end of the SDR is
overloaded.

Less of a pagermon issue and more of a SDR problem.

**Comment by DanrwAU** [comment]
The grey messages are just function codes, which are filtered by default. 

By default the pagermon client will only send alphanumeric messages to the server.
