### ISSUE TITLE
Block messages with same content

### ISSUE THREAD

**Issue by krisken** [pagermon/pagermon#503]
In Belgium, we got several messages per minute, that start with +++SWION+++P=$DIGIT, where $DIGIT can be anything between 0 and 99.  The CAP code can be anything.

Is it possible to ignore these messages, the same way we can ignore messages from the same CAP code?

Please see https://imgur.com/a/SyTItaM

**Comment by eopo** [comment]
Do you want to only ignore the repeating messages and keep the first one, or do you want to get rid of all of them?
If you don't need any of them, this is possible using the Filter plugin. Use the "Ignore Message" option and use a regex like `\+\+\+SWION\+\+\+P=\d{1,2}`
If you want to filter repetitions, a custom plugin with database queries is needed.
