### ISSUE TITLE
Define color and icon once in Aliasses

### ISSUE THREAD

**Issue by krisken** [pagermon/pagermon#504]
Is it possible to set the color and icon once (in Aliasses), and put a dropdown in Aliases to use it??

Eg I use "#00ca00" as color, "ambulance" as icon and safe it as "ambulance".  Then, when I add a new alias, I can use the pre-defined "ambulance" and everything is set to the correct icon and color.

**Comment by eopo** [comment]
Interesting Idea.
Do you think of it as a kind of template to make creation of new alias easier, or do you think of it as a reference, so existing Aliases would change the color and or icon, if the definition is changed?

**Comment by geelongmicrosoldering** [comment]
> Interesting Idea. Do you think of it as a kind of template to make creation of new alias easier, or do you think of it as a reference, so existing Aliases would change the color and or icon, if the definition is changed?

i love this, alias templates would make my life easier. have you started on this at all?

**Comment by geelongmicrosoldering** [comment]
@eopo assuming you haven't started it and I didn't just step on your toes (noticed you self-assigned)

How about this?

https://user-images.githubusercontent.com/14150258/165453056-3336dd30-9fb2-4e15-89fd-0606bd9f5d61.mov

You add/edit filters from Settings, like you would Text Matching. They are stored in config file
![aliasTemplate2](https://user-images.githubusercontent.com/14150258/165453319-bf1b4369-c58b-4dc6-930f-1f871f647510.png)

I can submit a PR with this.
Potentially, I can close [this PR](https://github.com/pagermon/pagermon/pull/512) and submit a new one with both helpers

**Comment by DanrwAU** [comment]
Fixed in #514
