### ISSUE TITLE
Help - Custom language and icon

### ISSUE THREAD

**Issue by denperss11** [pagermon/pagermon#511]
Hi im new to this one. 

First this is so amazing work thank you so much. 

- Is it possible to customize language ? 
- Is it possible to set custom logo and icon ? 
- is it possible to change design on login screen ?

**Comment by eopo** [comment]
Hello @denperss11
The answer is: Kind of.
In fact, everything you mentioned is completely possible, but not very convenient. There isn't any kind of option for setting language, title, logo or things like that (at least currently, this might change in the future).
However you can edit the files you find in ```server/themes``` and make PagerMon look like you want it to, but you'll need to have at least a basic understanding of HTML and JavaScript. Simply replace any terms you want to translate, include images you want to be shown or replace the existing files, edit the whole HTML-Structure according to your needs, make some CSS changes (For example to make some kind of a dark mode), ...
