### ISSUE TITLE
How can I change language settings to swedish?

### ISSUE THREAD

**Issue by sa7bnb** [pagermon/pagermon#529]
How can I change language settings to swedish?
Have tried adding -C SE to reader.sh file, but doesn't get it to decode anything then?
Is it that it is too old version of multimon-ng in pagermon (raspberrypi img)?

Example of inputting in reader.sh
rtl_fm -f 148.6500M -p 2 -g 49 -l 0 -s22050 - |
multimon-ng -q -b1 -c se -a POCSAG512 -a POCSAG1200 -f alpha -t raw /dev/stdin

Examples of incorrect characters and message i received :
Sjukv}rdslarm would be : Sjukvårdslarm
Hj{rtstopp would be : Hjärtstopp

**Comment by eopo** [comment]
Please head to [EliasOenal/multimon-ng](https://github.com/EliasOenal/multimon-ng) for that, as it's an multimon-ng issue and not a pagermon issue
