### ISSUE TITLE
Api Telegram

### ISSUE THREAD

**Issue by gg33fr** [pagermon/pagermon#534]
hello, I followed the tutorial to put the telegram  api in pagermon , but I don't understand the instructions at:
Enter this chat ID in Telegram section in Pagermon Alias
Where should I put it, if someone can tell me, it's in telegram but where?
Thanks

**Comment by geelongmicrosoldering** [comment]
In Pagermon under each Alias, there is a field to enter the Chat ID. This allows messages from each alias to go to different telegram groups/recipients if you choose.

You have to edit an existing alias and/or create a new one to see the field

**Comment by gg33fr** [comment]
A big thank-you
I have been looking since yesterday
