### ISSUE TITLE
API inconsistency regarding timestamp

### ISSUE THREAD

**Issue by eopo** [pagermon/pagermon#553]
The API as well as the internal code does use the variable "datetime" as well as the variable "timestamp" for a messages timestamp. All cases should use one name for the same thing.

I propose changing the name to "timestamp". API calls from older code using "datetime" should be possible to but lead to a deprecation warning in the log.

**Comment by geelongmicrosoldering** [comment]
Yeah i remember this being discussed at some point. Will probably require me to change some code in various integrations but im all for the uniformity. It probably should have been addressed sooner
