### ISSUE TITLE
Text bug 

### ISSUE THREAD

**Issue by 112bzo** [pagermon/pagermon#564]
**Describe the bug**
texts bug.

I see in the admin "Grip 3" but in the overview i see Gr**ee**p 3

<a href="https://ibb.co/Mgwp9Vt"><img src="https://i.ibb.co/Mgwp9Vt/grip3-label-juist.png" alt="grip3-label-juist" border="0"></a> <a href="https://ibb.co/d0hr9zG"><img src="https://i.ibb.co/d0hr9zG/grip3-label-onjuist.png" alt="grip3-label-onjuist" border="0"></a>

Its a text bug i think. 

Version : PagerMon 0.3.12-beta

**Comment by geelongmicrosoldering** [comment]
There's no bug.

You are using Chrome. Chrome asked if you want to translate English to Dutch. You clicked yes.

English: Grip = Dutch: Greep

Turn off google translate. This isn't an issue with pagermon

**Comment by 112bzo** [comment]
Oh i'am stupid....... Tnx thats te isseu
