### ISSUE TITLE
Icons not displayed

### ISSUE THREAD

**Issue by radar85** [pagermon/pagermon#567]
**Describe the bug**
MDI Icons are not showing in the home or alias screens

**To Reproduce**
1. Click on Admin
2. Click on Alias

**Expected behavior**
The icons for the aliases should appear

**Comment by andrewerrington** [comment]
I noticed this too, in the last couple of days the icons are not showing up in the web interface. It's a problem with fontawesome. Something must have changed recently.

**Comment by DanrwAU** [comment]
This is fixed in 0.3.13.

You will need to visit the fontawesome website and register your own kit. See the instructions in the release notes
