### ISSUE TITLE
Rasberry Pi, RTL-SDR V4 issue

### ISSUE THREAD

**Issue by aleluja123** [pagermon/pagermon#569]
Hey.

I am using Pagermon on Raspberry Pi and RTL SDR V3 dongle.

I would like to swap it with V dongle.

I use this tutorial for drivers:
_***NOTE***
If you previously installed librtlsdr-dev via the package manager you should remove this first BEFORE installing these drivers. To completely remove these drivers use the following commands

sudo apt purge ^librtlsdr
sudo rm -rvf /usr/lib/librtlsdr* /usr/include/rtl-sdr* /usr/local/lib/librtlsdr* /usr/local/include/rtl-sdr* /usr/local/include/rtl_* /usr/local/bin/rtl_*

***Now install the drivers***

sudo apt update
sudo apt install libusb-1.0-0-dev git cmake
git clone https://github.com/rtlsdrblog/rtl-sdr-blog
cd rtl-sdr-blog/
mkdir build
cd build
cmake ../ -DINSTALL_UDEV_RULES=ON
make
sudo make install
sudo cp ../rtl-sdr.rules /etc/udev/rules.d/
sudo ldconfig
echo 'blacklist dvb_usb_rtl28xxu' | sudo tee --append /etc/modprobe.d/blacklist-dvb_usb_rtl28xxu.conf_

Here is my reader.sh output:
rtl_fm -d 0 -M fm -E dc -F 0 -A fast -f 163.400M -s22050 - |
multimon-ng -q -b0 -c -a POCSAG512 -a POCSAG1200 -a POCSAG2400 -f alpha -t raw /dev/stdin |
node reader.js

But it won't provide any output.
With V3 there was no issue.

Any idea what to do?
Cheers.

**Comment by DanrwAU** [comment]
Issues with different SDR's  aren't a pagermon app issue. I suggest heading over t the discord and you might find someone who can help.
