### ISSUE TITLE
Make Badge clickable

### ISSUE THREAD

**Issue by manzil-infinity180** [pagermon/pagermon#573]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
<img width="1680" alt="Screenshot 2023-09-27 at 3 18 12 PM" src="https://github.com/pagermon/pagermon/assets/119070053/0a53715b-a583-4720-84b9-bda7ba22a3ad">

**Additional context**

👷‍♀️Want to work on it

**Comment by WizRd0** [comment]
A screenshot of the github project with a topic "Make Badge clickable" isn't helpful or descriptive, especially as the text above the desktop screenshot isn't filled out.

You might want to add in the actual details before the bug report is closed without consideration.
