### ISSUE TITLE
How to simply upgrade from old version  0.3.5-beta

### ISSUE THREAD

**Issue by techofix4u** [pagermon/pagermon#575]
Hi All,
A while ago (Pagermon version 0.3.5-beta), I setup Pagermon. It has been running great. It took a lot of effort to get it going, but I was pleased to get there and have been successful decoding since.
I'm not too good with Linux and I want to upgrade my current install from 0.3.5-beta to the latest version.
Is there a simple way to do this without losing my reader.sh config, my long file splitting config and all of my cap codes and descriptions?
If someone could supply the terminal commands that would be perfect.
Please let me know if you need further information on my install.
Many thanks.

**Comment by f5gkw** [comment]
Idem, same as you :)

**Comment by erikklavora** [comment]
> Hi All, A while ago (Pagermon version 0.3.5-beta), I setup Pagermon. It has been running great. It took a lot of effort to get it going, but I was pleased to get there and have been successful decoding since. I'm not too good with Linux and I want to upgrade my current install from 0.3.5-beta to the latest version. Is there a simple way to do this without losing my reader.sh config, my long file splitting config and all of my cap codes and descriptions? If someone could supply the terminal commands that would be perfect. Please let me know if you need further information on my install. Many thanks.

Hi @techofix4u , do you have a how to of what you did to get Pagermon working? I'm scratching my head but not working... i mean, it works from client to server but not when i try to pass pocsag messages from rtl_fm through multimon-ng to node reader.js I get: `Uncaught SyntaxError: Unexpected identifier`

**Comment by DanrwAU** [comment]
Support is available in #support on the project discord.
