### ISSUE TITLE
All New Messages are displayed on Filtered results

### ISSUE THREAD

**Issue by bullseye555** [pagermon/pagermon#588]
**Describe the bug**
When a filter is applied and on Page 1 of the filter, _all_ new messages are displayed in the filter list
![image](https://github.com/pagermon/pagermon/assets/28804763/713704f7-23c7-4acc-9d0f-e1fb90049486)

**To Reproduce**
1. Go to the main page
2. Apply a filter (in the screenshot above, this is for _FS90 Patterson River_)
3. Stay on the page and wait for new decoded messages to show
4. Once new messages are decoded, they will appear

**Expected behavior**
Either
1. Only new messages for the filtered results should show (so, in the above scenario, only new messages for FS90); or,
2. No new messages should appear

**Environment information:**
 - OS: Pagemon Pi Image - with manual upgrade to v0.3.13
 - Other details: Using custom themes, but have confirmed this also occurs on the _Default_ theme
![image](https://github.com/pagermon/pagermon/assets/28804763/4c326884-e6ad-4617-bf59-b5148d875d86)

**Comment by bullseye555** [comment]
Updating this - I've also noticed that that when this is filtered, the _new_ decodes don't lengthen the result page, but replace the filtered decodes

EG: this filter has 7 results
![image](https://github.com/pagermon/pagermon/assets/28804763/aff39e9e-6815-4445-8ebd-7224b29c3bdf)

Instead of the next 13 results appearing on top and the original 7 moving down the page (with the default 20 results shown), it will replace them with the next 7 decodes (with the process continuing for every new decode)
![image](https://github.com/pagermon/pagermon/assets/28804763/e432106b-c2e7-4bb8-bec7-a5ad0156b58f)


Additional debug - this appears to only occur when filtering by _Alias_
Filtering by Agency, Capcode, or specific custom text does not appear to be an issue (at least, in my testing) - and I don't have multiple sources to see if filtering by Source is an issue

**Comment by eopo** [comment]
> Updating this - I've also noticed that that when this is filtered, the new decodes don't lengthen the result page, but replace the filtered decodes
Is gonna be fixed by #597

I'll have a look for the other issue. Currently, we do send all messages via socket and then filter client side, if we want them to be shown. That seems to not work in your case.

**Comment by DanrwAU** [comment]
Fixed by #597
