### ISSUE TITLE
Bulk add hundreds of aliases?

### ISSUE THREAD

**Issue by chudgoo** [pagermon/pagermon#60]
If someone had a CSV file of all the capcodes and associated users, it would be nice if there a way to bulk add them to the PagerMon database.  If this is already possible, I apologize for making a new issue of it.

**Comment by davidmckenzie** [comment]
That's kind of a thing in the import.js in the client dir - it just parses a filters.ini file from PDW. It is in CSV format, so you could either format your CSV to match, or modify the import script to select different columns :)

https://github.com/davidmckenzie/pagermon/blob/master/client/samples/filters.ini

https://github.com/davidmckenzie/pagermon/blob/master/client/import.js

A lot of the import.js script is based on my personal use of the filters.ini, so generally does need a little modification to suit local envs. E.g. I assume that the alias will be in the format of "Agency - Brigade/Unit"

**Comment by davidmckenzie** [comment]
Reopening this as I'd like to create a generic csv importer

**Comment by davidmckenzie** [comment]
Closing - in 0.3.0 release
